Add Microsoft.Build 16.8.0 and all its dependencies
dotnet/source-build-reference-packages pull request #384
Opened 2022-05-11 20:52 UTC by MichaelSimons

This is required for building Nuget.Client.

2022-05-18 19:48 UTC, lbussell approved these changes

2022-05-18 22:00 UTC, crummel approved these changes

2022-05-20 14:47 UTC, MichaelSimons commented
I needed a couple edit to support building in a tarball context with 7.0 previously source-built artifacts.

2022-05-20 15:56 UTC, crummel requested changes

2022-05-20 16:00 UTC, MichaelSimons commented on eng/Build.props
> +  <Target Name="BuildDependencyPackageProjects"
Thanks for catching that.  A last minute refactoring on my part.  Fixed.

2022-05-20 16:09 UTC, crummel approved these changes

2022-05-20 17:44 UTC, merged